Repository imbhargav5/rooks, pull requests merged in 2019-12, with the labels that each got.

#190 Fix typo on website
  packages/docusaurus/pages/en/index.js
Labels: PR: Docs :memo:

#191 Improvements to docusaurus website
  packages/docusaurus/pages/en/versions.js
  packages/docusaurus/sidebars.json
  packages/docusaurus/siteConfig.js
  packages/docusaurus/versioned_sidebars/version-3.5.0-sidebars.json
  packages/docusaurus/versions.json
Labels: PR: Docs :memo:

#192 Add rebase github action
  .github/workflows/rebase.yml
Labels: PR: Internal :house:

#193 Fix rebase action
  .github/workflows/canary.yml
  .github/workflows/greetings.yml
  .github/workflows/rebase.yml
  .github/workflows/release.yml
  .github/workflows/version-bump.yml
Labels: PR: Internal :house:

#150 Feat/144/add use fullscreen
  packages/fullscreen/.babelrc
  packages/fullscreen/.eslintrc
  packages/fullscreen/.npmignore
  packages/fullscreen/README.md
  packages/fullscreen/index.d.ts
  packages/fullscreen/package.json
  packages/fullscreen/src/index.ts
  packages/fullscreen/src/useFullscreen.ts
  packages/fullscreen/test/index.spec.js
  packages/storybook/src/fullscreen.js
  packages/storybook/src/index.js
Labels: PR: New Feature :rocket:

#195 Remove travis integration
  .travis.yml
  packages/boundingclientrect-ref/README.md
  packages/countdown/README.md
  packages/docusaurus/docs/use-boundingclientrect-ref.md
  packages/docusaurus/docs/use-countdown.md
  packages/docusaurus/docs/use-fork-ref.md
  packages/docusaurus/docs/use-geolocation.md
  packages/docusaurus/docs/use-intersection-observer-ref.md
  packages/docusaurus/docs/use-isomorphic-effect.md
  packages/docusaurus/docs/use-mutation-observer-ref.md
  packages/docusaurus/docs/use-outside-click-ref.md
  packages/docusaurus/versioned_docs/version-3.5.0/use-boundingclientrect-ref.md
  packages/docusaurus/versioned_docs/version-3.5.0/use-countdown.md
  packages/docusaurus/versioned_docs/version-3.5.0/use-fork-ref.md
  packages/docusaurus/versioned_docs/version-3.5.0/use-geolocation.md
  packages/docusaurus/versioned_docs/version-3.5.0/use-intersection-observer-ref.md
  packages/docusaurus/versioned_docs/version-3.5.0/use-isomorphic-effect.md
  packages/docusaurus/versioned_docs/version-3.5.0/use-mutation-observer-ref.md
  packages/docusaurus/versioned_docs/version-3.5.0/use-outside-click-ref.md
  packages/fork-ref/README.md
  packages/geolocation/README.md
  packages/intersection-observer-ref/README.md
  packages/isomorphic-effect/README.md
  packages/mutation-observer-ref/README.md
  packages/outside-click-ref/README.md
Labels: PR: Internal :house:

#194 Feat/144/add use fullscreen (#150)
  packages/fullscreen/.babelrc
  packages/fullscreen/.eslintrc
  packages/fullscreen/.npmignore
  packages/fullscreen/README.md
  packages/fullscreen/index.d.ts
  packages/fullscreen/package.json
  packages/fullscreen/src/index.ts
  packages/fullscreen/src/useFullscreen.ts
  packages/fullscreen/test/index.spec.js
  packages/storybook/src/fullscreen.js
  packages/storybook/src/index.js
Labels: PR: New Feature :rocket:
